Standardise "Invalid --state" error message

diff --git a/type/__apt_mark/gencode-remote b/type/__apt_mark/gencode-remote
--- a/type/__apt_mark/gencode-remote
+++ b/type/__apt_mark/gencode-remote
@@ -55,7 +55,7 @@ in
         echo "apt-mark ${state_should} ${name} > /dev/null"
         ;;
     (*)
-        echo "Unknown state: ${state_should}" >&2
+        printf 'Invalid --state: %s\n' "${state_should}" >&2
         exit 1
         ;;
 esac
diff --git a/type/__directory/gencode-remote b/type/__directory/gencode-remote
--- a/type/__directory/gencode-remote
+++ b/type/__directory/gencode-remote
@@ -150,7 +150,7 @@ in
       fi
       ;;
    (*)
-      echo "Unknown state: ${state_should}" >&2
+      printf 'Invalid --state: %s\n' "${state_should}" >&2
       exit 1
       ;;
 esac
diff --git a/type/__key_value/gencode-remote b/type/__key_value/gencode-remote
--- a/type/__key_value/gencode-remote
+++ b/type/__key_value/gencode-remote
@@ -76,7 +76,7 @@ in
         esac
         ;;
     (*)
-        echo "Unknown state: ${state_should}" >&2
+        printf 'Invalid --state: %s\n' "${state_should}" >&2
         exit 1
         ;;
 esac
diff --git a/type/__link/gencode-remote b/type/__link/gencode-remote
--- a/type/__link/gencode-remote
+++ b/type/__link/gencode-remote
@@ -33,7 +33,7 @@ in
         lnopt=''
         ;;
     (*)
-        echo "Unknown link type: ${type}" >&2
+        printf 'Invalid --type: %s\n' "${type}" >&2
         exit 1
         ;;
 esac
@@ -75,7 +75,7 @@ in
         fi
         ;;
     (*)
-        echo "Unknown state: ${state_should}" >&2
+        printf 'Invalid --state: %s\n' "${state_should}" >&2
         exit 1
         ;;
 esac
diff --git a/type/__package_apk/gencode-remote b/type/__package_apk/gencode-remote
--- a/type/__package_apk/gencode-remote
+++ b/type/__package_apk/gencode-remote
@@ -42,7 +42,7 @@ in
         echo 'removed' >> "${__messages_out:?}"
         ;;
     (*)
-        echo "Unknown state: ${state_should}" >&2
+        printf 'Invalid --state: %s\n' "${state_should}" >&2
         exit 1
         ;;
 esac
diff --git a/type/__package_apt/gencode-remote b/type/__package_apt/gencode-remote
--- a/type/__package_apt/gencode-remote
+++ b/type/__package_apt/gencode-remote
@@ -158,7 +158,7 @@ EOF
         fi
         ;;
     (*)
-        echo "Unknown state: ${state_should}" >&2
+        printf 'Invalid --state: %s\n' "${state_should}" >&2
         exit 1
         ;;
 esac
diff --git a/type/__package_dpkg/gencode-remote b/type/__package_dpkg/gencode-remote
--- a/type/__package_dpkg/gencode-remote
+++ b/type/__package_dpkg/gencode-remote
@@ -48,5 +48,8 @@ in
         echo "dpkg ${action} ${__object_id%%_*}"
         echo "removed (${action})" >> "${__messages_out:?}"
         ;;
-    (*)  echo "ERROR: unknown state '${state}'" >&2 ;;
+    (*)
+        printf 'Invalid --state: %s\n' "${state}" >&2
+        exit 1
+        ;;
 esac
diff --git a/type/__package_opkg/gencode-remote b/type/__package_opkg/gencode-remote
--- a/type/__package_opkg/gencode-remote
+++ b/type/__package_opkg/gencode-remote
@@ -53,7 +53,7 @@ in
 		echo 'removed' >>"${__messages_out:?}"
 		;;
 	(*)
-		printf 'Unknown state: %s\n' "${state_should}" >&2
+		printf 'Invalid --state: %s\n' "${state_should}" >&2
 		exit 1
 		;;
 esac
diff --git a/type/__package_pkg_openbsd/gencode-remote b/type/__package_pkg_openbsd/gencode-remote
--- a/type/__package_pkg_openbsd/gencode-remote
+++ b/type/__package_pkg_openbsd/gencode-remote
@@ -121,7 +121,7 @@ EOF
 		echo 'removed' >> "${__messages_out:?}"
 		;;
 	(*)
-		echo "Unknown state: ${state_should}" >&2
+		printf 'Invalid --state: %s\n' "${state_should}" >&2
 		exit 1
 		;;
 esac
diff --git a/type/__pacman_conf/manifest b/type/__pacman_conf/manifest
--- a/type/__pacman_conf/manifest
+++ b/type/__pacman_conf/manifest
@@ -75,7 +75,7 @@ then
         exit 0
 
     else
-        echo "ERROR: Unknown state: ${state}" >&2
+        printf 'Invalid --state: %s\n' "${state}" >&2
         exit 0
     fi
 fi
@@ -140,7 +140,7 @@ eof
             --state absent
 
     else
-        echo "ERROR: Unknown state: ${state}" >&2
+        printf 'Invalid --state: %s\n' "${state}" >&2
     fi
 
 fi
diff --git a/type/__pacman_conf_integrate/manifest b/type/__pacman_conf_integrate/manifest
--- a/type/__pacman_conf_integrate/manifest
+++ b/type/__pacman_conf_integrate/manifest
@@ -54,6 +54,6 @@ then
 
 else
 
-    echo "ERROR: Unknown state: ${state}" >&2
+    printf 'Invalid --state: %s\n' "${state}" >&2
 
 fi
diff --git a/type/__pyvenv/gencode-remote b/type/__pyvenv/gencode-remote
--- a/type/__pyvenv/gencode-remote
+++ b/type/__pyvenv/gencode-remote
@@ -66,7 +66,7 @@ in
     (absent)
         ;;
     (*)
-        echo "Unknown state: ${state_should}" >&2
+        printf 'Invalid --state: %s\n' "${state_should}" >&2
         exit 1
         ;;
 esac
diff --git a/type/__systemd_unit/gencode-remote b/type/__systemd_unit/gencode-remote
--- a/type/__systemd_unit/gencode-remote
+++ b/type/__systemd_unit/gencode-remote
@@ -85,7 +85,7 @@ in
         echo 'masked' >> "${__messages_out:?}"
         ;;
     (*)
-        echo "Unsupported unit status: ${desired_enablement_state}" >&2
+        printf 'Invalid --enablement-state: %s\n' "${desired_enablement_state}" >&2
         exit 1
         ;;
 esac
diff --git a/type/__user/gencode-remote b/type/__user/gencode-remote
--- a/type/__user/gencode-remote
+++ b/type/__user/gencode-remote
@@ -199,5 +199,5 @@ then
         echo "userdel $*" >>"${__messages_out:?}"
     fi
 else
-    echo "Invalid state ${state}" >&2
+    printf 'Invalid --state: %s\n' "${state}" >&2
 fi
diff --git a/type/__zypper_repo/gencode-remote b/type/__zypper_repo/gencode-remote
--- a/type/__zypper_repo/gencode-remote
+++ b/type/__zypper_repo/gencode-remote
@@ -101,7 +101,7 @@ in
         fi
         ;;
     (*)
-        echo "Unknown state: ${state}" >&2
+        printf 'Invalid --state: %s\n' "${state}" >&2
         exit 1
         ;;
 esac
diff --git a/type/__zypper_service/gencode-remote b/type/__zypper_service/gencode-remote
--- a/type/__zypper_service/gencode-remote
+++ b/type/__zypper_service/gencode-remote
@@ -85,7 +85,7 @@ in
         echo "zypper ${zypper_def_opts} ref"
         ;;
     (*)
-        echo "Unknown state: ${state_should}" >&2
+        printf 'Invalid --state: %s\n' "${state_should}" >&2
         exit 1
         ;;
 esac
