Use "assert pattern" instead of if ! ...
Replace occurrences of "if ! ..." with "... | { handler }" in cases when it is
not really used as a conditional but to check for a requirement/prerequisite and
handling an error condition in the block.

This way it is clearer that the code is not a conditional but instead it is to
handle an unexpected condition.

Such blocks usually end with "exit 1" :-)

diff --git a/type/__package_pkg_openbsd/gencode-remote b/type/__package_pkg_openbsd/gencode-remote
--- a/type/__package_pkg_openbsd/gencode-remote
+++ b/type/__package_pkg_openbsd/gencode-remote
@@ -84,18 +84,13 @@ in
 		cat <<EOF
 status=\$(pkg_add ${pkgopts} '${pkgid}' 2>&1 || :)
 
-if ! pkg_info -q -I 'inst:${pkgid}' | grep -q '^${name}-${version}.*${flavor}$' 2>/dev/null
-then
+pkg_info -q -I 'inst:${pkgid}' | grep -q '^${name}-${version}.*${flavor}$' 2>/dev/null || {
 	# We didn't find the package in the list of 'installed packages', so it failed.
 	# This is necessary because pkg_add doesn't return properly
 
-	if [ -z "\${status}" ]
-	then
-		status='Failed to add package, uncaught exception.'
-	fi
-	echo "Error: \${status}" >&2
+	printf 'Error: %s\n' "\${status:-Failed to add package, uncaught exception.}" >&2
 	exit 1
-fi
+}
 EOF
 		echo 'installed' >> "${__messages_out:?}"
 		;;
