Use skonfig-exported $__x variables only as ${__x:?}
Fixes SC2154 (warning): __x is referenced but not assigned.

diff --git a/type/__staged_file/gencode-local b/type/__staged_file/gencode-local
--- a/type/__staged_file/gencode-local
+++ b/type/__staged_file/gencode-local
@@ -21,11 +21,11 @@
 
 #set -x
 
-destination="$__object_id"
-source="$(cat "$__object/parameter/source")"
-stage_dir="$(cat "$__object/parameter/stage-dir")"
-state="$(cat "$__object/parameter/state")"
-fetch_command="$(cat "$__object/parameter/fetch-command")"
+destination="${__object_id:?}"
+source="$(cat "${__object:?}/parameter/source")"
+stage_dir="$(cat "${__object:?}/parameter/stage-dir")"
+state="$(cat "${__object:?}/parameter/state")"
+fetch_command="$(cat "${__object:?}/parameter/fetch-command")"
 stage_file="${stage_dir}/${destination}"
 stage_file_dir="${stage_file%/*}"
 source_file_name="${source##*/}"
@@ -48,7 +48,7 @@ fi
 
 
 get_file() {
-   if [ -f "$__object/parameter/prepare-command" ]; then
+   if [ -f "${__object:?}/parameter/prepare-command" ]; then
       fetch_and_prepare_file
    else
       fetch_file
@@ -68,7 +68,7 @@ fetch_and_prepare_file() {
    printf 'cd "$tmpdir"\n'
    # shellcheck disable=SC2059
    printf "$fetch_command > \"%s\"\\n" "$source" "$source_file_name"
-   prepare_command="$(cat "$__object/parameter/prepare-command")"
+   prepare_command="$(cat "${__object:?}/parameter/prepare-command")"
    # shellcheck disable=SC2059
    printf "$prepare_command > \"%s\"\\n" "$source_file_name" "$stage_file"
    printf 'cd - >/dev/null\n'
@@ -79,7 +79,7 @@ fetch_and_prepare_file() {
 cat << DONE
 verify_cksum() {
    cksum_is="\$(cksum "$stage_file" | cut -d' ' -f1,2)"
-   cksum_should="$(cut -d' ' -f1,2 "$__object/parameter/cksum")"
+   cksum_should="$(cut -d' ' -f1,2 "${__object:?}/parameter/cksum")"
    if [ "\$cksum_is" = "\$cksum_should" ]; then
       return 0
    else
@@ -98,7 +98,7 @@ fi
 
 cat << DONE
 verify_cksum || {
-   echo "Failed to verify checksum for $__object_name" >&2
+   echo "Failed to verify checksum for ${__object_name:?}" >&2
    exit 1
 }
 DONE
diff --git a/type/__systemd_service/gencode-remote b/type/__systemd_service/gencode-remote
--- a/type/__systemd_service/gencode-remote
+++ b/type/__systemd_service/gencode-remote
@@ -24,17 +24,17 @@
 
 
 # get name of the service
-name="$__object/parameter/name"
+name="${__object:?}/parameter/name"
 if [ -f "$name" ]; then
     name="$(cat "$name")"
 else
-    name="$__object_id"
+    name="${__object_id:?}"
 fi
 
 
 # read current status and parameters
-state="$(cat "$__object/explorer/state")"
-should="$(cat "$__object/parameter/state")"
+state="$(cat "${__object:?}/explorer/state")"
+should="$(cat "${__object:?}/parameter/state")"
 
 # if systemd/service does not exist
 if [ -z "$state" ]; then
@@ -61,11 +61,11 @@ if [ "$state" != "$should" ]; then
 fi
 
 # check if the action can be achieved if given
-if [ -f "$__object/parameter/action" ] \
+if [ -f "${__object:?}/parameter/action" ] \
     && [ -z "$required_action" ] && [ "$state" = "running" ]; then
 
     # there must be an action
-    action="$(cat "$__object/parameter/action")"
+    action="$(cat "${__object:?}/parameter/action")"
 
     # select the action to the required element
     case "$action" in
@@ -84,15 +84,15 @@ if [ -f "$__object/parameter/action" ] \
 
     # Make a special check: only do this action if a dependency did something
     # it is required that the dependencies write there action to $__messages_in
-    if [ -f "$__object/parameter/if-required" ]; then
+    if [ -f "${__object:?}/parameter/if-required" ]; then
         # exit here if there are no changes from the dependencies affected (nothing to do)
-        if ! grep -q -f "$__object/require" "$__messages_in"; then exit 0; fi
+        if ! grep -q -f "${__object:?}/require" "${__messages_in:?}"; then exit 0; fi
     fi
 fi
 
 # print the execution command if a action given
 if [ -n "$required_action" ]; then
     # also print it as message
-    echo "$required_action" >> "$__messages_out"
+    echo "$required_action" >> "${__messages_out:?}"
     echo "systemctl $required_action '$name'"
 fi
