Put braces around parameter expansions
Fixes SC2250: Prefer putting braces around variable references even when not strictly required.

diff --git a/type/__line/gencode-remote b/type/__line/gencode-remote
--- a/type/__line/gencode-remote
+++ b/type/__line/gencode-remote
@@ -33,14 +33,14 @@ fi
 state_should=$(cat "${__object:?}/parameter/state")
 state_is=$(cat "${__object:?}/explorer/state")
 
-if [ -z "$state_is" ]; then
-   printf 'The file "%s" is missing. Please create it before using %s on it.\n' "$file" "${__type##*/}" >&2
+if [ -z "${state_is}" ]; then
+   printf 'The file "%s" is missing. Please create it before using %s on it.\n' "${file}" "${__type##*/}" >&2
    exit 1
 fi
 
-if [ "$state_should" = "$state_is" ] || \
-	{ [ "$state_should" = "present" ] && [ "$state_is" = "matching" ] ;} || \
-	{ [ "$state_should" = "replace" ] && [ "$state_is" = "present" ] ;} ; then
+if [ "${state_should}" = "${state_is}" ] || \
+	{ [ "${state_should}" = "present" ] && [ "${state_is}" = "matching" ] ;} || \
+	{ [ "${state_should}" = "replace" ] && [ "${state_is}" = "present" ] ;} ; then
    # If state matches already, or 'present' is used and regex matches
    # or 'replace' is used and the exact line is present, then there is
    # nothing to do
@@ -64,9 +64,9 @@ fi
 
 add=0
 remove=0
-case $state_should in
+case ${state_should} in
    present|replace)
-      if [ "$state_is" = "wrongposition" ] || [ "$state_is" = "matching" ]; then
+      if [ "${state_is}" = "wrongposition" ] || [ "${state_is}" = "matching" ]; then
          echo updated >> "${__messages_out:?}"
          remove=1
       else
@@ -83,11 +83,11 @@ esac
 cat << DONE
 tmpfile=\$(mktemp ${file}.skonfig.XXXXXX)
 # preserve ownership and permissions of existing file
-if [ -f "$file" ]; then
-   cp -p "$file" "\$tmpfile"
+if [ -f "${file}" ]; then
+   cp -p "${file}" "\${tmpfile}"
 fi
 
-awk -v position="$position" -v needle="$needle" -v remove=$remove -v add=$add '
+awk -v position="${position}" -v needle="${needle}" -v remove=${remove} -v add=${add} '
 function _find(_text, _pattern) {
    if (needle == "regex") {
       return match(_text, _pattern)
@@ -131,8 +131,8 @@ END {
       print line
    }
 }
-' "$file" > "\$tmpfile"
-mv -f "\$tmpfile" "$file"
+' "${file}" > "\${tmpfile}"
+mv -f "\${tmpfile}" "${file}"
 DONE
 
 if [ -f "${__object:?}/parameter/onchange" ]; then
diff --git a/type/__package_dpkg/gencode-remote b/type/__package_dpkg/gencode-remote
--- a/type/__package_dpkg/gencode-remote
+++ b/type/__package_dpkg/gencode-remote
@@ -32,10 +32,10 @@ package=$(basename "${__object_id:?}")
 state_is=$(cat "${__object:?}/explorer/pkg_state")
 state_should=""
 
-[ "$state" = "absent" ] || state_should="$package"
-[ "$state_is" = "$state_should" ] && exit 0
+[ "${state}" = "absent" ] || state_should="${package}"
+[ "${state_is}" = "${state_should}" ] && exit 0
 
-case $state in
+case ${state} in
     present)
         echo "dpkg --install /var/cache/apt/archives/${__object_id:?}"
         echo "installed" >> "${__messages_out:?}"
@@ -44,8 +44,8 @@ case $state in
         [ -f "${__object:?}/parameter/purge-if-absent" ] \
             && action="--purge" \
             || action="--remove"
-        echo "dpkg $action ${__object_id%%_*}"
-        echo "removed ($action)" >> "${__messages_out:?}"
+        echo "dpkg ${action} ${__object_id%%_*}"
+        echo "removed (${action})" >> "${__messages_out:?}"
         ;;
-    *)  echo "ERROR: unknown state '$state'" >&2 ;;
+    *)  echo "ERROR: unknown state '${state}'" >&2 ;;
 esac
diff --git a/type/__package_pkg_freebsd/gencode-remote b/type/__package_pkg_freebsd/gencode-remote
--- a/type/__package_pkg_freebsd/gencode-remote
+++ b/type/__package_pkg_freebsd/gencode-remote
@@ -25,7 +25,7 @@ assert ()                 #  If condition false,
 
 	if [ -z "$2" ]          # Not enough parameters passed.
 	then
-		return $E_PARAM_ERR   # No damage done.
+		return ${E_PARAM_ERR}   # No damage done.
 	fi
 
 	lineno=$2
@@ -35,8 +35,8 @@ assert ()                 #  If condition false,
 		echo "Assertion failed:  \"$1\""
 		# shellcheck disable=SC2039
 		# shellcheck disable=SC3044
-		echo "File \"$0\", line $lineno, called by $(caller 0)"
-		exit $E_ASSERT_FAILED
+		echo "File \"$0\", line ${lineno}, called by $(caller 0)"
+		exit ${E_ASSERT_FAILED}
 	fi
 }
 
@@ -65,23 +65,23 @@ cmd=""
 # FIXME: This is ugly.
 execcmd(){
 	# Set the PACKAGESITE if we're ADDing a new package
-	if [ "$1" = "add" ] && [ -n "$pkgsite" ]; then
+	if [ "$1" = "add" ] && [ -n "${pkgsite}" ]; then
 		# Use http.../All/ if we know the exact version we want, use .../Latest/ otherwise
 		pkgsite="export PACKAGESITE=${pkgsite}"
-		[ -n "$version" ] && pkgsite="${pkgsite}/All/" || pkgsite="${pkgsite}/Latest/"
+		[ -n "${version}" ] && pkgsite="${pkgsite}/All/" || pkgsite="${pkgsite}/Latest/"
 		echo "${pkgsite}"
 	fi
 	echo "${2} 2>&- >&-"	# Silence the output of the command
 	echo "status=\$?"
-	echo "if [ \"\$status\" -ne \"0\" ]; then"
-	echo "	echo \"Error: ${cmd} exited nonzero with \$status\"'!' >&2"
+	echo "if [ \"\${status}\" -ne \"0\" ]; then"
+	echo "	echo \"Error: ${cmd} exited nonzero with \${status}\"'!' >&2"
 	echo "	exit 1"
 	echo "fi"
 }
 
-if [ -n "$curr_version" ]; then	# PKG *is* installed
-	if [ "$state" = "absent" ]; then	# Shouldn't be installed
-		if [ -n "$flavor" ]; then
+if [ -n "${curr_version}" ]; then	# PKG *is* installed
+	if [ "${state}" = "absent" ]; then	# Shouldn't be installed
+		if [ -n "${flavor}" ]; then
 			cmd="${rm_cmd} ${name}-${flavor}-${curr_version}"
 		else
 			cmd="${rm_cmd} ${name}-${curr_version}"
@@ -90,13 +90,13 @@ if [ -n "$curr_version" ]; then	# PKG *is* installed
 		echo "removed" >> "${__messages_out:?}"
 		exit 0
 	else	# Should be installed
-		if [ -n "$version" ]; then	# Want a specific version
-			if [ "$version" = "$curr_version" ]; then	# Current version is correct
+		if [ -n "${version}" ]; then	# Want a specific version
+			if [ "${version}" = "${curr_version}" ]; then	# Current version is correct
 				exit 0
 			else	# Current version is wrong, fix
-				#updatepkg "$name" "$version"
+				#updatepkg "${name}" "${version}"
 				# shellcheck disable=SC2039
-				assert "! ${version} = ${curr_version}" $LINENO
+				assert "! ${version} = ${curr_version}" ${LINENO}
 				cmd="${rm_cmd} ${name}-${curr_version}"
 				execcmd "remove" "${cmd}"
 				cmd="${add_cmd} -r ${name}-${version}"
@@ -108,15 +108,15 @@ if [ -n "$curr_version" ]; then	# PKG *is* installed
 		fi
 	fi
 else	# PKG *isn't* installed
-	if [ "$state" = "absent" ]; then	# Shouldn't be installed
+	if [ "${state}" = "absent" ]; then	# Shouldn't be installed
 		exit 0
-	elif [ "$state" = "present" ]; then	# Is not currently installed, should be
-		if [ -n "$flavor" ]; then
+	elif [ "${state}" = "present" ]; then	# Is not currently installed, should be
+		if [ -n "${flavor}" ]; then
 			cmd="${add_cmd} -r ${name}-${flavor}"
 		else
 			cmd="${add_cmd} -r ${name}"
 		fi
-		if [ -n "$version" ]; then
+		if [ -n "${version}" ]; then
 			cmd="${cmd}-${version}"
 		fi
 		execcmd "add" "${cmd}"
diff --git a/type/__package_pkgng_freebsd/gencode-remote b/type/__package_pkgng_freebsd/gencode-remote
--- a/type/__package_pkgng_freebsd/gencode-remote
+++ b/type/__package_pkgng_freebsd/gencode-remote
@@ -75,32 +75,32 @@ execcmd(){
        echo "ASSUME_ALWAYS_YES=yes pkg bootstrap >/dev/null 2>&1"
    fi
 
-   echo "$_cmd >/dev/null 2>&1"   # Silence the output of the command
+   echo "${_cmd} >/dev/null 2>&1"   # Silence the output of the command
    echo "status=\$?"
-   echo "if [ \"\$status\" -ne \"0\" ]; then"
-   echo "	echo \"Error: ${_cmd} exited nonzero with \$status\"'!' >&2"
+   echo "if [ \"\${status}\" -ne \"0\" ]; then"
+   echo "	echo \"Error: ${_cmd} exited nonzero with \${status}\"'!' >&2"
    echo "	exit 1"
    echo "fi"
 }
 
-if [ -n "$curr_version" ]; then  # PKG *is* installed
-   if [ -n "$repo" ]; then
+if [ -n "${curr_version}" ]; then  # PKG *is* installed
+   if [ -n "${repo}" ]; then
       cmd="-r ${repo} ${name}"
    else
       cmd=${name}
    fi
-   if [ -n "$flavor" ]; then
+   if [ -n "${flavor}" ]; then
       cmd="${cmd}-${flavor}"
    fi
    # PKG is supposed to be removed
-   if [ "$state" = "absent" ]; then
+   if [ "${state}" = "absent" ]; then
       execcmd "rm" "${cmd}"
    # PKG is supposed to be installed to a particular version
-   elif [ -n "$version" ] && [ "$version" != "$curr_version" ]; then
-      if [ "$upgrade" = "true" ]; then
+   elif [ -n "${version}" ] && [ "${version}" != "${curr_version}" ]; then
+      if [ "${upgrade}" = "true" ]; then
          execcmd "upg" "${cmd}"
       else
-         printf 'Version %s is already installed and pkg-ng cannot upgrade directly to version %s.\nTo upgrade to the latest version, use the --upgrade flag.\n' "$curr_version" "$version" >&2
+         printf 'Version %s is already installed and pkg-ng cannot upgrade directly to version %s.\nTo upgrade to the latest version, use the --upgrade flag.\n' "${curr_version}" "${version}" >&2
          exit 1
       fi
    # PKG is supposed to be installed to the latest version
@@ -108,22 +108,22 @@ if [ -n "$curr_version" ]; then  # PKG *is* installed
       :  # Do nothing.
    fi
 else  # PKG *isn't* installed
-   if [ "$state" = "absent" ]; then # Shouldn't be installed
+   if [ "${state}" = "absent" ]; then # Shouldn't be installed
       exit 0
    else  # Should be installed
-      if [ -n "$repo" ]; then
+      if [ -n "${repo}" ]; then
          cmd="-r ${repo} ${name}"
       else
          cmd=${name}
       fi
-      if [ -n "$flavor" ]; then
+      if [ -n "${flavor}" ]; then
          cmd="${cmd}-${flavor}"
       fi
-      if [ -n "$version" ]; then
+      if [ -n "${version}" ]; then
          cmd="${cmd}-${version}"
       fi
 
-      execcmd "add" "$cmd"
+      execcmd "add" "${cmd}"
       exit 0
    fi
 fi
diff --git a/type/__systemd_service/gencode-remote b/type/__systemd_service/gencode-remote
--- a/type/__systemd_service/gencode-remote
+++ b/type/__systemd_service/gencode-remote
@@ -25,8 +25,8 @@
 
 # get name of the service
 name="${__object:?}/parameter/name"
-if [ -f "$name" ]; then
-    name=$(cat "$name")
+if [ -f "${name}" ]; then
+    name=$(cat "${name}")
 else
     name=${__object_id:?}
 fi
@@ -37,8 +37,8 @@ state=$(cat "${__object:?}/explorer/state")
 should=$(cat "${__object:?}/parameter/state")
 
 # if systemd/service does not exist
-if [ -z "$state" ]; then
-    printf "systemd or service '%s' does not exist!\n" "$name" >&2
+if [ -z "${state}" ]; then
+    printf "systemd or service '%s' does not exist!\n" "${name}" >&2
     exit 1
 fi
 
@@ -47,28 +47,28 @@ fi
 required_action=""
 
 # check the state of the service that should be
-if [ "$state" != "$should" ]; then
+if [ "${state}" != "${should}" ]; then
     # select what to do to get the $should state
-    case $should in
+    case ${should} in
         running)
-            if [ "$state" = "stopped" ]; then required_action="start"; fi
+            if [ "${state}" = "stopped" ]; then required_action="start"; fi
             ;;
 
         stopped)
-            if [ "$state" = "running" ]; then required_action="stop"; fi
+            if [ "${state}" = "running" ]; then required_action="stop"; fi
             ;;
     esac
 fi
 
 # check if the action can be achieved if given
 if [ -f "${__object:?}/parameter/action" ] \
-    && [ -z "$required_action" ] && [ "$state" = "running" ]; then
+    && [ -z "${required_action}" ] && [ "${state}" = "running" ]; then
 
     # there must be an action
     action=$(cat "${__object:?}/parameter/action")
 
     # select the action to the required element
-    case $action in
+    case ${action} in
         restart)
             required_action="restart"
             ;;
@@ -78,7 +78,7 @@ if [ -f "${__object:?}/parameter/action" ] \
             ;;
 
         *)
-            printf "action '%s' does not exist!" "$action" >&2
+            printf "action '%s' does not exist!" "${action}" >&2
             exit 2
     esac
 
@@ -91,8 +91,8 @@ if [ -f "${__object:?}/parameter/action" ] \
 fi
 
 # print the execution command if a action given
-if [ -n "$required_action" ]; then
+if [ -n "${required_action}" ]; then
     # also print it as message
-    echo "$required_action" >> "${__messages_out:?}"
-    echo "systemctl $required_action '$name'"
+    echo "${required_action}" >> "${__messages_out:?}"
+    echo "systemctl ${required_action} '${name}'"
 fi
diff --git a/type/__user/gencode-remote b/type/__user/gencode-remote
--- a/type/__user/gencode-remote
+++ b/type/__user/gencode-remote
@@ -45,7 +45,7 @@ shorten_property() {
     create-home) ret="-m";;
     system) ret="-r";;
     esac
-    echo "$ret"
+    echo "${ret}"
 }
 
 quote_ifneeded() {
@@ -99,29 +99,29 @@ do_user() {
 	unset _util_name _user_name
 }
 
-if [ "$state" = "present" ]; then
+if [ "${state}" = "present" ]; then
     cd "${__object:?}/parameter"
     if grep -q "^${name}:" "${__object:?}/explorer/passwd"; then
        for property in *; do
-          new_value=$(cat "$property")
+          new_value=$(cat "${property}")
           unset current_value
 
           file="${__object:?}/explorer/passwd"
 
-          case $property in
+          case ${property} in
              gid)
-                if echo "$new_value" | grep -q '^[0-9][0-9]*$'; then
+                if echo "${new_value}" | grep -q '^[0-9][0-9]*$'; then
                    field=4
                 else
                    # We were passed a group name.  Compare the gid in
                    # the user's /etc/passwd entry with the gid of the
                    # group returned by the group explorer.
                    gid_from_group=$(awk -F: '{ print $3 }' "${__object:?}/explorer/group")
-                   gid_from_passwd=$(awk -F: '{ print $4 }' "$file")
-                   if [ "$gid_from_group" != "$gid_from_passwd" ]; then
-                      current_value=$gid_from_passwd
+                   gid_from_passwd=$(awk -F: '{ print $4 }' "${file}")
+                   if [ "${gid_from_group}" != "${gid_from_passwd}" ]; then
+                      current_value=${gid_from_passwd}
                    else
-                      current_value=$new_value
+                      current_value=${new_value}
                    fi
                 fi
              ;;
@@ -141,13 +141,13 @@ if [ "$state" = "present" ]; then
 
           # If we haven't already set $current_value above, pull it from the
           # appropriate file/field.
-          if [ -z "$current_value" ]; then
+          if [ -z "${current_value}" ]; then
              export field
-             current_value=$(awk -F: '{ print $ENVIRON["field"] }' < "$file")
+             current_value=$(awk -F: '{ print $ENVIRON["field"] }' < "${file}")
           fi
 
-          if [ "$new_value" != "$current_value" ]; then
-              set -- "$@" "$(shorten_property "$property")" "$new_value"
+          if [ "${new_value}" != "${current_value}" ]; then
+              set -- "$@" "$(shorten_property "${property}")" "${new_value}"
           fi
        done
 
@@ -161,19 +161,19 @@ if [ "$state" = "present" ]; then
     else
         echo add >> "${__messages_out:?}"
         for property in *; do
-            [ "$property" = "state" ] && continue
-            [ "$property" = "remove-home" ] && continue
-            new_value=$(cat "$property")
-            if [ -z "$new_value" ];then       # Boolean values have no value
-              set -- "$@" "$(shorten_property "$property")"
+            [ "${property}" = "state" ] && continue
+            [ "${property}" = "remove-home" ] && continue
+            new_value=$(cat "${property}")
+            if [ -z "${new_value}" ];then       # Boolean values have no value
+              set -- "$@" "$(shorten_property "${property}")"
             else
-              set -- "$@" "$(shorten_property "$property")" "$new_value"
+              set -- "$@" "$(shorten_property "${property}")" "${new_value}"
             fi
         done
 
        do_user add "${name}" "$@"
     fi
-elif [ "$state" = "absent" ]; then
+elif [ "${state}" = "absent" ]; then
     if grep -q "^${name}:" "${__object:?}/explorer/passwd"; then
         #user exists, but state != present, so delete it
         set --
@@ -185,5 +185,5 @@ elif [ "$state" = "absent" ]; then
         echo "userdel $*" >>"${__messages_out:?}"
     fi
 else
-    echo "Invalid state $state" >&2
+    echo "Invalid state ${state}" >&2
 fi
