Various changes

diff --git a/type/__package_pkgng_freebsd/gencode-remote b/type/__package_pkgng_freebsd/gencode-remote
--- a/type/__package_pkgng_freebsd/gencode-remote
+++ b/type/__package_pkgng_freebsd/gencode-remote
@@ -1,6 +1,7 @@
 #!/bin/sh -e
 #
 # 2014 Jake Guffey (jake.guffey at eprotex.com)
+# 2025 Dennis Camera (dennis.camera at riiengineering.ch)
 #
 # This file is part of skonfig-base.
 #
@@ -18,7 +19,7 @@
 # along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
 #
 
-if [ -f "${__object:?}/parameter/name" ]
+if test -f "${__object:?}/parameter/name"
 then
    name=$(cat "${__object:?}/parameter/name")
 else
@@ -28,7 +29,7 @@ fi
 flavor=$(cat "${__object:?}/parameter/flavor")
 version=$(cat "${__object:?}/parameter/version")
 
-if [ -f "${__object:?}/parameter/upgrade" ]
+if test -f "${__object:?}/parameter/upgrade"
 then
    upgrade='true'
 else
@@ -50,8 +51,8 @@ upg_cmd='pkg upgrade -y'
 cmd=''
 
 # Print the command to be executed
-# Parms: $1 -- mode, "rm", "add", or "upg"
-#        $2 -- the command to be echoed
+# Params: $1 -- mode, "rm", "add", or "upg"
+#         $2 -- the command to be echoed
 execcmd(){
    _cmd=''
 
@@ -59,15 +60,15 @@ execcmd(){
    in
       (add)
          _cmd="${add_cmd} $2"
-         echo 'installed' >> "${__messages_out:?}"
+         echo 'installed' >>"${__messages_out:?}"
          ;;
       (rm)
          _cmd="${rm_cmd} $2"
-         echo 'removed' >> "${__messages_out:?}"
+         echo 'removed' >>"${__messages_out:?}"
          ;;
       (upg)
          _cmd="${upg_cmd} $2"
-         echo 'installed' >> "${__messages_out:?}"
+         echo 'installed' >>"${__messages_out:?}"
          ;;
       (*)
          printf "Error. Don't understand command: %s" "$1" >&2
@@ -80,66 +81,46 @@ execcmd(){
        echo 'ASSUME_ALWAYS_YES=yes pkg bootstrap >/dev/null 2>&1'
    fi
 
-   echo "${_cmd} >/dev/null 2>&1"   # Silence the output of the command
-   echo "status=\$?"
-   echo "if [ \"\${status}\" -ne \"0\" ]"
-   echo "then"
-   echo "	echo \"Error: ${_cmd} exited nonzero with \${status}\"'!' >&2"
+   echo "${_cmd} >/dev/null 2>&1 || {"   # Silence the output of the command
+   echo "	echo \"Error: ${_cmd} exited nonzero with \$?\"'!' >&2"
    echo "	exit 1"
-   echo "fi"
+   echo "}"
 }
 
-if [ -n "${curr_version}" ]
-then  # PKG *is* installed
-   if [ -n "${repo}" ]
+if test -n "${curr_version}"
+then
+   # PKG *is* installed
+   cmd="${repo:+-r ${repo} }${name}${flavor:+-${flavor}}"
+
+   if test "${state}" = 'absent'
    then
-      cmd="-r ${repo} ${name}"
-   else
-      cmd=${name}
-   fi
-   if [ -n "${flavor}" ]
+      # PKG is supposed to be removed
+      execcmd rm "${cmd}"
+   elif test -n "${version}" && test "${version}" != "${curr_version}"
    then
-      cmd="${cmd}-${flavor}"
-   fi
-   # PKG is supposed to be removed
-   if [ "${state}" = 'absent' ]
-   then
-      execcmd 'rm' "${cmd}"
-   # PKG is supposed to be installed to a particular version
-   elif [ -n "${version}" ] && [ "${version}" != "${curr_version}" ]
-   then
-      if [ "${upgrade}" = 'true' ]
+      # PKG is supposed to be installed to a particular version
+      if ${upgrade?}
       then
-         execcmd 'upg' "${cmd}"
+         execcmd upg "${cmd}"
       else
          printf 'Version %s is already installed and pkg-ng cannot upgrade directly to version %s.\nTo upgrade to the latest version, use the --upgrade flag.\n' "${curr_version}" "${version}" >&2
          exit 1
       fi
-   # PKG is supposed to be installed to the latest version
    else
+      # PKG is supposed to be installed to the latest version
       :  # Do nothing.
    fi
-else  # PKG *isn't* installed
-   if [ "${state}" = 'absent' ]
-   then # Shouldn't be installed
-      exit 0
-   else  # Should be installed
-      if [ -n "${repo}" ]
-      then
-         cmd="-r ${repo} ${name}"
-      else
-         cmd=${name}
-      fi
-      if [ -n "${flavor}" ]
-      then
-         cmd="${cmd}-${flavor}"
-      fi
-      if [ -n "${version}" ]
-      then
-         cmd="${cmd}-${version}"
-      fi
+else
+   # PKG *isn't* installed
 
-      execcmd 'add' "${cmd}"
+   if test "${state}" = 'absent'
+   then
+      # Shouldn't be installed
+      exit 0
+   else
+      # Should be installed
+      cmd="${repo:+-r ${repo} }${name}${flavor:+-${flavor}}${version:+-${version}}"
+      execcmd add "${cmd}"
       exit 0
    fi
 fi
diff --git a/type/__pacman_conf/manifest b/type/__pacman_conf/manifest
--- a/type/__pacman_conf/manifest
+++ b/type/__pacman_conf/manifest
@@ -45,41 +45,47 @@ contains_element() {
 
     for key
     do
-        if [ "${key}" = "${target}" ]
-        then
-            MATCH=true
-            return 0
-        fi
+        case ${key}
+        in
+            ("${target}")
+                MATCH=true
+                return 0
+                ;;
+        esac
     done
-    MATCH=false
 }
 
-if [ -n "${file}" ]
+if test -n "${file}"
 then
-    __file "${sec_path}/plain_file_${file}"\
-        --state exists --mode 666
+    __file "${sec_path}/plain_file_${file}" \
+        --state exists \
+        --mode 666
 
-    if [ "${state}" = 'present' ]
-    then
-
-        require="__file/${sec_path}/plain_file_${file}" __key_value "${file}_${key}" \
-            --file "${sec_path}/plain_file_${file}" --key "${key}" --value "${value}" --delimiter ' = '
-
-        exit 0
-
-    elif [ "${state}" = 'absent' ]
-    then
-        require="__file/${sec_path}/plain_file_${file}" __key_value "${file}_${key}" \
+    case ${state}
+    in
+        (present)
+            require="__file/${sec_path}/plain_file_${file}" \
+            __key_value "${file}_${key}" \
+                --file "${sec_path}/plain_file_${file}" \
+                --delimiter ' = ' \
+                --key "${key}" \
+                --value "${value}"
+            exit 0
+            ;;
+        (absent)
+            require="__file/${sec_path}/plain_file_${file}" \
+            __key_value "${file}_${key}" \
                 --state absent
-        exit 0
-
-    else
-        printf 'Invalid --state: %s\n' "${state}" >&2
-        exit 0
-    fi
+            exit 0
+            ;;
+        (*)
+            printf 'Invalid --state: %s\n' "${state}" >&2
+            exit 0
+            ;;
+    esac
 fi
 
-if [ "${section}" = 'options' ]
+if test "${section}" = 'options'
 then
 
     __file "${sec_path}/${section}"\
@@ -92,54 +98,68 @@ eof
 
     if ${MATCH?}
     then
-        if [ "${value}" = 'on' ]
-        then
-            require="__file/${sec_path}/${section}" __line "${key}_${value}" \
-                --file "${sec_path}/${section}" --line "${key}"
-        elif [ "${value}" = 'off' ]
-        then
-            require="__file/${sec_path}/${section}" __line "${key}_${value}" \
-                --file "${sec_path}/${section}" --line "${key}" --state absent
-        fi
-
+        case ${value}
+        in
+            (on)
+                require="__file/${sec_path}/${section}" \
+                __line "${key}_${value}" \
+                    --file "${sec_path}/${section}" \
+                    --line "${key}"
+                ;;
+            (off)
+                require="__file/${sec_path}/${section}" \
+                __line "${key}_${value}" \
+                    --state absent \
+                    --file "${sec_path}/${section}" \
+                    --line "${key}"
+                ;;
+        esac
     else
         contains_element "${key}" "${allowed_option_keys}"
 
         if ${MATCH?}
         then
-            require="__file/${sec_path}/${section}" __key_value "${section}_${key}" \
-                    --file "${sec_path}/${section}" --key "${key}" --value "${value}" --delimiter ' = '
+            require="__file/${sec_path}/${section}" \
+            __key_value "${section}_${key}" \
+                --file "${sec_path}/${section}" \
+                --delimiter ' = ' \
+                --key "${key}" \
+                --value "${value}"
         else
             echo "Key: ${key} is not valid. Have a look at man pacman.conf" >&2
         fi
     fi
-
 else
-        __file "${sec_path}/repo_${section}"\
-            --state exists --mode 666 --source - << eof
+    __file "${sec_path}/repo_${section}" \
+        --state exists \
+        --mode 666 \
+        --source - <<EOF
 [${section}]
-eof
-    if [ "${state}" = 'present' ]
-    then
+EOF
 
-        #check if key is valid
-        contains_element "${key}" "${allowed_repo_keys}"
-        if ! ${MATCH?}
-        then
-            exit
-        fi
+    case ${state}
+    in
+        (present)
+            #check if key is valid
+            contains_element "${key}" "${allowed_repo_keys}"
 
-        require="__file/${sec_path}/repo_${section}" __key_value "${section}_${key}" \
-                --file "${sec_path}/repo_${section}" --key "${key}" --value "${value}" --delimiter ' = '
+            ${MATCH?} || exit
 
-    elif [ "${state}" = 'absent' ]
-    then
-
-        require="__file/${sec_path}/repo_${section}" __key_value "${section}_${key}" \
-            --state absent
-
-    else
-        printf 'Invalid --state: %s\n' "${state}" >&2
-    fi
-
+            require="__file/${sec_path}/repo_${section}" \
+            __key_value "${section}_${key}" \
+                --file "${sec_path}/repo_${section}" \
+                --delimiter ' = ' \
+                --key "${key}" \
+                --value "${value}"
+            ;;
+        (absent)
+            require="__file/${sec_path}/repo_${section}" \
+            __key_value "${section}_${key}" \
+                --state absent
+            ;;
+        (*)
+            printf 'Invalid --state: %s\n' "${state}" >&2
+            exit 1
+            ;;
+    esac
 fi
