[type/__file] Lint and reorganisation of scripts

diff --git a/type/__file/gencode-local b/type/__file/gencode-local
--- a/type/__file/gencode-local
+++ b/type/__file/gencode-local
@@ -2,6 +2,7 @@
 #
 # 2011-2012 Nico Schottelius (nico-cdist at schottelius.org)
 # 2013-2022 Steven Armstrong (steven-cdist armstrong.cc)
+# 2022 Dennis Camera (cdist at dtnr.ch)
 #
 # This file is part of cdist.
 #
@@ -19,109 +20,122 @@
 # along with cdist. If not, see <http://www.gnu.org/licenses/>.
 #
 
-destination="/$__object_id"
-state_should="$(cat "$__object/parameter/state")"
-type="$(cat "$__object/explorer/type")"
+quote() { printf '%s\n' "$*" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'/"; }
 
-[ "$state_should" = "exists" ] && [ "$type" = "file" ] && exit 0 # nothing to do
+destination="/${__object_id:?}"
+state_should=$(cat "${__object:?}/parameter/state")
+type_is=$(cat "${__object:?}/explorer/type")
 
-if [ "$state_should" = "pre-exists" ]; then
-	if [ -f "$__object/parameter/source" ]; then
-		echo "--source cannot be used with --state pre-exists" >&2
-		exit 1
-	fi
+upload_file() {
+	# source $1
+	# destination $2
 
-	case $type in
-		file)
-			# nothing to do
-			exit 0
-			;;
-		none)
-			printf 'File "%s" does not exist\n' "$destination" >&2
-			exit 1
-			;;
-		directory|symlink)
-			printf 'File "%s" exists and is a %s, but should be a regular file\n' "$destination" "$type" >&2
-			exit 1
-			;;
-		*)
-			printf 'File or directory "%s" is in an unknown state\n' "$destination" >&2
-			exit 1
-			;;
-	esac
-fi
+	# tell gencode-remote that we created or uploaded a file and that it
+	# must set all attributes no matter what the explorer retreived
+	mkdir "${__object:?}/files"
+	touch "${__object:?}/files/file-uploaded"
 
-upload_file=
-create_file=
-if [ "$state_should" = "present" ] || [ "$state_should" = "exists" ]; then
-	if [ ! -f "$__object/parameter/source" ]; then
-		remote_stat="$(cat "$__object/explorer/stat")"
-		if [ -z "$remote_stat" ]; then
-			create_file=1
-			echo create >> "$__messages_out"
-		fi
+	# upload file to temp location
+	_upload_destination=$(mktemp -u "/__cdist${2:?}.cdist.XXXXXX" | sed 's|^/__cdist||')
+	# Yes, we are aware that this is a race condition.
+	# However:
+	# a) cdist usually writes to directories that are not user writable
+	#	 (probably > 99.9%)
+	# b) if they are user owned, the user / attacker always wins
+	#	 (probably < 0.1%)
+	# c) the only case which we could improve are tmp directories and we
+	#	 don't think managing tmp directories with cdist is a typical case
+	#	 ("the rest %)"
+
+	# Tell gencode-remote to where we uploaded the file so it can move
+	# it to its final destination.
+	echo "${_upload_destination}" >"${__object:?}/files/upload-destination"
+
+	# IPv6 fix
+	if expr "${__target_host:?}" : '[0-9a-fA-F:]\{1,\}$' >/dev/null
+	then
+		_destination_host="[${__target_host:?}]"
 	else
-		source="$(cat "$__object/parameter/source")"
-		if [ "$source" = "-" ]; then
-			source="$__object/stdin"
-		fi
-		if [ ! -f "$source" ]; then
-			echo "Source \"$source\" does not exist." >&2
-			exit 1
-		else
-			if [ "$type" != "file" ]; then
-				# destination is not a regular file, upload source to replace it
-				upload_file=1
-				echo upload >> "$__messages_out"
-			else
-				local_cksum="$(cksum < "$source")"
-				remote_cksum="$(cat "$__object/explorer/cksum")"
-				if [ "$local_cksum" != "$remote_cksum" ]; then
-					# destination is a regular file, but not the right one
-					upload_file=1
-				fi
-			fi
-		fi
+		_destination_host=${__target_host:?}
 	fi
-	if [ "$create_file" ] || [ "$upload_file" ]; then
-		# tell gencode-remote that we created or uploaded a file and that it must
-		# set all attributes no matter what the explorer retreived
-		mkdir "$__object/files"
-		touch "$__object/files/set-attributes"
 
-		if [ "$create_file" ]; then
-			# When creating an empty file we create it locally and then
-			# upload it so that permissions can be set before moving the file
-			# into place.
-			source="$__object/files/empty"
-			touch "$source"
-		fi
+	cat <<-EOF
+	${__remote_copy:?} $(quote "${1:?}") $(quote "${_destination_host}"):$(quote "${_upload_destination}")
+	EOF
 
-		# upload file to temp location
-		upload_destination="$(mktemp -u "/__cdist${destination}.cdist.XXXXXXXXXX" | sed 's|^/__cdist||')"
-		# Yes, we are aware that this is a race condition.
-		# However:
-		# a) cdist usually writes to directories that are not user writable
-		#	 (probably > 99.9%)
-		# b) if they are user owned, the user / attacker always wins
-		#	 (probably < 0.1%)
-		# c) the only case which we could improve are tmp directories and we
-		#	 don't think managing tmp directories with cdist is a typical case
-		#	 ("the rest %)"
+	unset _destination_host _upload_destination
+}
 
-		# Tell gencode-remote to where we uploaded the file so it can move
-		# it to its final destination.
-		echo "$upload_destination" > "$__object/files/upload-destination"
-
-		# IPv6 fix
-		if echo "${__target_host}" | grep -q -E '^[0-9a-fA-F:]+$'
+case ${state_should}
+in
+	(pre-exists)
+		if test -f "${__object:?}/parameter/source"
 		then
-			 my_target_host="[${__target_host}]"
-		else
-			 my_target_host="${__target_host}"
+			echo '--source cannot be used with --state pre-exists' >&2
+			exit 1
 		fi
-		cat << DONE
-$__remote_copy "$source" "${my_target_host}:${upload_destination}"
-DONE
-	fi
-fi
+
+		case ${type_is}
+		in
+			(file)
+				# nothing to do
+				exit 0
+				;;
+			(none)
+				printf 'File "%s" does not exist\n' "${destination}" >&2
+				exit 1
+				;;
+			(directory|symlink)
+				printf 'File "%s" exists and is a %s, but should be a regular file\n' "${destination}" "${type_is}" >&2
+				exit 1
+				;;
+			(*)
+				printf 'File or directory "%s" is in an unknown state\n' "${destination}" >&2
+				exit 1
+				;;
+		esac
+		;;
+	(present|exists)
+		upload_file=false
+
+		if test "${type_is}" != 'file'
+		then
+			# destination is not a regular file
+			upload_file=true
+		elif test "${state_should}" = 'present' \
+		&& ! cksum <"${source}" | cmp -s "${__object:?}/explorer/cksum" -
+		then
+			# destination is a regular file, but not the right one
+			upload_file=true
+		fi
+
+		if ${upload_file?}
+		then
+			# determine source
+			if test -f "${__object:?}/parameter/source"
+			then
+				source=$(cat "${__object:?}/parameter/source")
+				if test "${source}" = '-'
+				then
+					source="${__object:?}/stdin"
+				fi
+
+				test -f "${source}" || {
+					printf 'Source "%s" does not exist.\n' "${source}" >&2
+					exit 1
+				}
+
+				echo upload >>"${__messages_out:?}"
+			else
+				# when creating an empty file we create it locally and then
+				# upload it so that permissions can be set before moving the file
+				# into place.
+				source=/dev/null
+
+				echo create >>"${__messages_out:?}"
+			fi
+
+			upload_file "${source}" "${destination}"
+		fi
+		;;
+esac
diff --git a/type/__file/gencode-remote b/type/__file/gencode-remote
--- a/type/__file/gencode-remote
+++ b/type/__file/gencode-remote
@@ -2,6 +2,7 @@
 #
 # 2011-2013 Nico Schottelius (nico-cdist at schottelius.org)
 # 2013-2022 Steven Armstrong (steven-cdist armstrong.cc)
+# 2022 Dennis Camera (cdist at dtnr.ch)
 #
 # This file is part of cdist.
 #
@@ -19,106 +20,113 @@
 # along with cdist. If not, see <http://www.gnu.org/licenses/>.
 #
 
-destination="/$__object_id"
-state_should="$(cat "$__object/parameter/state")"
-type="$(cat "$__object/explorer/type")"
-stat_file="$__object/explorer/stat"
-fire_onchange=''
+quote() { printf '%s\n' "$*" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'/"; }
+
+destination="/${__object_id:?}"
+state_should=$(cat "${__object:?}/parameter/state")
+stat_file="${__object:?}/explorer/stat"
+fire_onchange=false
 
 get_current_value() {
-	if [ -s "$stat_file" ]; then
-		_name="$1"
-		_value="$2"
-		case "$_value" in
-			[0-9]*)
+	if test -s "${stat_file}"
+	then
+		_name=$1
+		_value=$2
+		case ${_value}
+		in
+			([0-9]*)
 				_index=2
 				;;
-			*)
+			(*)
 				_index=3
 				;;
 		esac
-		awk '/'"$_name"':/ { print $'$_index' }' "$stat_file"
+		awk "/${_name}:/ { print \$$((_index)) }" "${stat_file}"
 		unset _name _value _index
 	fi
 }
 
 set_group() {
-	echo "chgrp '$1' '$destination'"
-	echo "chgrp '$1'" >> "$__messages_out"
-	fire_onchange=1
+	printf 'chgrp %s %s\n' "$(quote "$1")" "$(quote "${destination}")"
+	printf 'chgrp %s\n' "$(quote "$1")" >>"${__messages_out:?}"
+	fire_onchange=true
 }
 
 set_owner() {
-	echo "chown '$1' '$destination'"
-	echo "chown '$1'" >> "$__messages_out"
-	fire_onchange=1
+	printf 'chown %s %s\n' "$(quote "$1")" "$(quote "${destination}")"
+	printf 'chown %s\n' "$(quote "$1")" >>"${__messages_out:?}"
+	fire_onchange=true
 }
 
 set_mode() {
-	echo "chmod '$1' '$destination'"
-	echo "chmod '$1'" >> "$__messages_out"
-	fire_onchange=1
+	printf 'chmod %s %s\n' "$(quote "$1")" "$(quote "${destination}")"
+	printf 'chmod %s\n' "$(quote "$1")" >>"${__messages_out:?}"
+	fire_onchange=true
 }
 
-case "$state_should" in
-	present|exists)
-		if [ -f "$__object/files/upload-destination" ]; then
-			final_destination="$destination"
+case ${state_should}
+in
+	(present|exists)
+		if test -f "${__object:?}/files/upload-destination"
+		then
+			final_destination=${destination}
 			# We change the 'global' $destination variable here so we can
 			# change attributes of the new/uploaded file before moving it
 			# to it's final destination.
-			destination="$(cat "$__object/files/upload-destination")"
+			destination=$(cat "${__object:?}/files/upload-destination")
 		fi
+
 		# Note: Mode - needs to happen last as a chown/chgrp can alter mode by
 		#  clearing S_ISUID and S_ISGID bits (see chown(2))
-		for attribute in group owner mode; do
-			if [ -f "$__object/parameter/$attribute" ]; then
-				value_should="$(cat "$__object/parameter/$attribute")"
+		for attribute in group owner mode
+		do
+			test -f "${__object:?}/parameter/${attribute}" || continue
 
-				# format mode in four digits => same as stat returns
-				if [ "$attribute" = mode ]; then
-					# Convert to four-digit octal number (printf interprets
-					# strings with leading 0s as octal!)
-					value_should=$(printf '%04o' "0${value_should}")
-				fi
+			value_should=$(cat "${__object:?}/parameter/${attribute}")
 
-				value_is="$(get_current_value "$attribute" "$value_should")"
-				if [ -f "$__object/files/set-attributes" ] || [ "$value_should" != "$value_is" ]; then
-					"set_$attribute" "$value_should"
-				fi
+			# format mode in four digits => same as stat returns
+			if test "${attribute}" = 'mode' && expr "${value_should}" : '[0-9]' >/dev/null
+			then
+				# Convert to four-digit octal number (printf interprets
+				# strings with leading 0s as octal!)
+				value_should=$(printf '%04o' "0${value_should}")
+			fi
+
+			value_is=$(get_current_value "${attribute}" "${value_should}")
+			if test -f "${__object:?}/files/file-uploaded" \
+			|| test "${value_should}" != "${value_is}"
+			then
+				"set_${attribute}" "${value_should}"
 			fi
 		done
-		if [ -f "$__object/files/upload-destination" ]; then
+
+		if test -n "${final_destination-}"
+		then
 			# move uploaded file into place
-			printf 'rm -rf "%s"\n' "$final_destination"
-			printf 'mv "%s" "%s"\n' "$destination" "$final_destination"
-		fi
-		if [ -f "$__object/files/set-attributes" ]; then
-			# set-attributes is created if file is created or uploaded in gencode-local
-			fire_onchange=1
+			# printf 'rm -rf %s\n' "$(quote "${final_destination}")"
+			printf 'mv -f %s %s\n' "$(quote "${destination}")" "$(quote "${final_destination}")"
 		fi
 		;;
-
-	absent)
-		if [ "$type" = "file" ] || [ "$type" = "symlink" ]; then
-			echo "rm -f '$destination'"
-			echo remove >> "$__messages_out"
-			fire_onchange=1
-		fi
+	(pre-exists)
 		;;
-
-	pre-exists)
-		:
+	(absent)
+		type_is=$(cat "${__object:?}/explorer/type")
+		case ${type_is}
+		in
+			(file|symlink)
+				printf 'rm -f %s\n' "$(quote "${destination}")"
+				echo remove >>"${__messages_out:?}"
+				fire_onchange=true
+				;;
+		esac
 		;;
-
-	*)
-		echo "Unknown state: $state_should" >&2
+	(*)
+		printf 'Invalid --state: %s\n' "${state_should}" >&2
 		exit 1
 		;;
 esac
 
-if [ -f "$__object/parameter/onchange" ]; then
-	if [ -n "$fire_onchange" ]; then
-		cat "$__object/parameter/onchange"
-	fi
+if ${fire_onchange?} && test -s "${__object:?}/parameter/onchange"
+then
+	cat "${__object:?}/parameter/onchange"
 fi
