Replace unnecessary double quotes

diff --git a/type/__dpkg_architecture/gencode-remote b/type/__dpkg_architecture/gencode-remote
--- a/type/__dpkg_architecture/gencode-remote
+++ b/type/__dpkg_architecture/gencode-remote
@@ -27,7 +27,7 @@ main_arch=$(cat "${__object:?}/explorer/architecture")
 
 # Exit here if dpkg do not work (empty explorer)
 if [ -z "${main_arch}" ]; then
-    echo "dpkg is not available or unable to detect a architecture!" >&2
+    echo 'dpkg is not available or unable to detect a architecture!' >&2
     exit 1
 fi
 
@@ -35,16 +35,16 @@ fi
 # Check if requested architecture is the main one
 if [ "${arch_wanted}" = "${main_arch}" ]; then
     # higher than present; we can not remove it
-    state_is="present"
-    caution="yes"
+    state_is='present'
+    caution='yes'
 
 # Check if the architecture not already used
 elif grep -qFx "${arch_wanted}" "${__object:?}/explorer/foreign-architectures"; then
-    state_is="present"
+    state_is='present'
 
 # arch does not exist
 else
-    state_is="absent"
+    state_is='absent'
 fi
 
 
@@ -55,7 +55,7 @@ if [ "${state_is}" != "${state_should}" ]; then
             # print add code
             printf "dpkg --add-architecture '%s'\n" "${arch_wanted}"
             # updating the index to make the new architecture available
-            echo "apt update"
+            echo 'apt update'
 
             echo added >> "${__messages_out:?}"
             ;;
diff --git a/type/__group/explorer/gshadow b/type/__group/explorer/gshadow
--- a/type/__group/explorer/gshadow
+++ b/type/__group/explorer/gshadow
@@ -26,13 +26,13 @@ os=$("${__explorer:?}/os")
 
 not_supported() {
 	echo "Your operating system (${os}) is currently not supported." >&2
-	echo "Cannot extract group information." >&2
-	echo "Please contribute an implementation for it if you can." >&2
+	echo 'Cannot extract group information.' >&2
+	echo 'Please contribute an implementation for it if you can.' >&2
 	exit 1
 }
 
 case ${os} in
-	"freebsd"|"netbsd")
+	freebsd|netbsd)
 		echo "${os} does not have getent gshadow" >&2
 		exit 0
 	;;
diff --git a/type/__ssh_authorized_keys/manifest b/type/__ssh_authorized_keys/manifest
--- a/type/__ssh_authorized_keys/manifest
+++ b/type/__ssh_authorized_keys/manifest
@@ -25,14 +25,14 @@ file=$(cat "${__object:?}/explorer/file")
 
 if [ ! -f "${__object:?}/parameter/nofile" ] && [ -z "${file}" ]
 then
-	echo "Cannot determine path of authorized_keys file" >&2
+	echo 'Cannot determine path of authorized_keys file' >&2
 	exit 1
 fi
 
 if [ ! -f "${__object:?}/parameter/noparent" ] || [ ! -f "${__object:?}/parameter/nofile" ]; then
    group=$(cut -d':' -f 1 "${__object:?}/explorer/group")
    if [ -z "${group}" ]; then
-      echo "Failed to get owners group from explorer." >&2
+      echo 'Failed to get owners group from explorer.' >&2
       exit 1
    fi
 
diff --git a/type/__ssh_dot_ssh/manifest b/type/__ssh_dot_ssh/manifest
--- a/type/__ssh_dot_ssh/manifest
+++ b/type/__ssh_dot_ssh/manifest
@@ -24,13 +24,13 @@ state=$(cat "${__object:?}/parameter/state")
 
 group=$(cut -d':' -f 1 "${__object:?}/explorer/group")
 if [ -z "${group}" ]; then
-    echo "Failed to get owners group from explorer." >&2
+    echo 'Failed to get owners group from explorer.' >&2
     exit 1
 fi
 
 home=$(cut -d':' -f 6 "${__object:?}/explorer/passwd")
 if [ -z "${home}" ]; then
-   echo "Failed to get home directory from explorer." >&2
+   echo 'Failed to get home directory from explorer.' >&2
    exit 1
 fi
 ssh_directory="${home}/.ssh"
