[type/__localedef] Lint

diff --git a/type/__localedef/gencode-remote b/type/__localedef/gencode-remote
--- a/type/__localedef/gencode-remote
+++ b/type/__localedef/gencode-remote
@@ -1,7 +1,7 @@
 #!/bin/sh -e
 #
 # 2013-2019 Nico Schottelius (nico-cdist at schottelius.org)
-# 2020,2025 Dennis Camera (dennis.camera at riiengineering.ch)
+# 2020,2023,2025 Dennis Camera (dennis.camera at riiengineering.ch)
 #
 # This file is part of skonfig-base.
 #
@@ -19,8 +19,18 @@
 # along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
 #
 
+shquot() {
+	sed -e "s/'/'\\\\''/g" -e "1s/^/'/" -e "\$s/\$/'/" <<-EOF
+	$*
+	EOF
+}
+
+# shellcheck source=SCRIPTDIR/files/lib/locale.sh
 . "${__type:?}/files/lib/locale.sh"
+# shellcheck source=SCRIPTDIR/files/lib/glibc.sh
 . "${__type:?}/files/lib/glibc.sh"
+
+os=$(cat "${__global:?}/explorer/os")
 
 state_is=$(cat "${__object:?}/explorer/state")
 state_should=$(cat "${__object:?}/parameter/state")
@@ -28,8 +38,8 @@ state_should=$(cat "${__object:?}/parameter/state")
 case ${state_should}
 in
 	("${state_is}")
-		# NOTE: If state explorer fails (e.g. locale(1) missing), the following check
-		#       will always fail and let definition/removal run.
+		# NOTE: If state explorer fails (e.g. locale(1) missing), the following
+		#       check will always fail and let definition/removal run.
 		exit 0
 		;;
 	(present|absent)
@@ -40,15 +50,17 @@ in
 		;;
 esac
 
-locale=${__object_id:?}
-os=$(cat "${__global:?}/explorer/os")
-
-if expr "${locale}" : '.*/' >/dev/null
-then
-	printf 'Paths as locales are not supported.\n' >&2
-	printf '__object_id is: %s\n' "${locale}" >&2
-	exit 1
-fi
+case ${__object_id:?}
+in
+	(*/*)
+		printf 'Paths as locales are not supported.\n' >&2
+		printf '__object_id is: %s\n' "${locale}" >&2
+		exit 1
+		;;
+	(*)
+		locale=${__object_id:?}
+		;;
+esac
 
 : "${lang=}" "${codeset=}" "${modifier=}"  # declare variables for shellcheck
 parse_locale "${locale}" lang codeset modifier
@@ -74,12 +86,12 @@ in
 				input=$(format_locale "${lang}" '' "${modifier}")
 				cat <<-EOF
 				set --
-				if test -e '${aliasfile}'
+				if test -e $(shquot "${aliasfile}")
 				then
-					set -- -A '${aliasfile}'
+					set -- -A $(shquot "${aliasfile}")
 				fi
 
-				localedef -i '${input}' -f '${codeset}' "\$@" '${locale}'
+				localedef -i $(shquot "${input}") -f $(shquot "${codeset}") "\$@" $(shquot "${locale}")
 				EOF
 				;;
 			(absent)
@@ -88,7 +100,7 @@ in
 				cat <<-EOF
 				while read -r _alias _localename
 				do
-				    if test "\${_localename}" = '$(format_locale "${lang}" "${codeset}")'
+				    if test "\${_localename}" = $(shquot "$(format_locale "${lang}" "${codeset}")")
 				    then
 				        localedef --delete-from-archive "\${_alias}"
 				    fi
@@ -97,7 +109,8 @@ in
 
 				if test "${state_is}" = present
 				then
-					printf "localedef --delete-from-archive '%s'\n" "${main_localename}"
+					printf "localedef --delete-from-archive %s\n" \
+						"$(shquot "${main_localename}")"
 				fi
 				;;
 		esac
@@ -106,10 +119,13 @@ in
 		case ${state_should}
 		in
 			(present)
-				if expr "$(grep -oe '^[0-9]*' "${__global:?}/explorer/os_version")" '>=' 11 >/dev/null
+				if expr "$(grep -o -e '^[0-9]*' "${__global:?}/explorer/os_version")" '>=' 11 >/dev/null
 				then
 					# localedef(1) is available with FreeBSD >= 11
-					printf "localedef -i '%s' -f '%s' '%s'\n" "${input}" "${codeset}" "${locale}"
+					printf "localedef -i %s -f %s %s\n" \
+						"$(shquot "${input}")" \
+						"$(shquot "${codeset}")" \
+						"$(shquot "${locale}")"
 				else
 					printf 'localedef(1) was added to FreeBSD starting with version 11.\n' >&2
 					printf 'Please upgrade your FreeBSD installation to use %s.\n' "${__type##*/}" >&2
@@ -117,7 +133,7 @@ in
 				fi
 				;;
 			(absent)
-				printf "rm -R '/usr/share/locale/%s'\n" "${locale}"
+				printf "rm -R %s\n" "$(shquot "/usr/share/locale/${locale}")"
 				;;
 		esac
 		;;
