[type/__user] Lint

diff --git a/type/__user/gencode-remote b/type/__user/gencode-remote
--- a/type/__user/gencode-remote
+++ b/type/__user/gencode-remote
@@ -4,7 +4,7 @@
 # 2011 Nico Schottelius (nico-cdist at schottelius.org)
 # 2013 Daniel Heule (hda at sfs.biz)
 # 2018 Thomas Eckert (tom at it-eckert.de)
-# 2022 Dennis Camera (dennis.camera at riiengineering.ch)
+# 2022,2024 Dennis Camera (dennis.camera at riiengineering.ch)
 #
 # This file is part of skonfig-base.
 #
@@ -25,27 +25,33 @@
 name=${__object_id:?}
 
 os=$(cat "${__global:?}/explorer/os")
-
-state=$(cat "${__object:?}/parameter/state")
+state_should=$(cat "${__object:?}/parameter/state")
 
 # We need to shorten options for both usermod and useradd since on some
 # systems (such as *BSD, Darwin) those commands do not handle GNU style long
 # options.
 shorten_property() {
-    unset -v ret
-    case $1
-    in
-        (comment) ret='-c';;
-        (home) ret='-d';;
-        (gid) ret='-g';;
-        (groups) ret='-G';;
-        (password) ret='-p';;
-        (shell) ret='-s';;
-        (uid) ret='-u';;
-        (create-home) ret='-m';;
-        (system) ret='-r';;
-    esac
-    echo "${ret}"
+	case $1
+	in
+		(comment)
+			echo '-c' ;;
+		(home)
+			echo '-d' ;;
+		(gid)
+			echo '-g' ;;
+		(groups)
+			echo '-G' ;;
+		(password)
+			echo '-p' ;;
+		(shell)
+			echo '-s' ;;
+		(uid)
+			echo '-u' ;;
+		(create-home)
+			echo '-m' ;;
+		(system)
+			echo '-r' ;;
+	esac
 }
 
 quote_ifneeded() {
@@ -71,7 +77,7 @@ quote_ifneeded() {
 do_user() {
 	_util_name=user$1
 	_user_name=$2
-	shift; shift
+	shift 2
 
 	set -- "${_util_name}" "$@"
 
@@ -90,6 +96,7 @@ do_user() {
 			echo 'PATH=/bin:/sbin:/usr/bin:/usr/sbin'
 			;;
 	esac
+
 	# append user name as last argument
 	set -- "$@" "${_user_name}"
 
@@ -99,105 +106,124 @@ do_user() {
 	unset -v _util_name _user_name
 }
 
-if [ "${state}" = 'present' ]
-then
-    cd "${__object:?}/parameter"
-    if cut -d: -f1 "${__object:?}/explorer/passwd" | grep -qxF -e "${name}"
-    then
-       for property in *
-       do
-          new_value=$(cat "${property}")
-          unset -v current_value
+case ${state_should}
+in
+	(present)
+		cd "${__object:?}/parameter"
 
-          file="${__object:?}/explorer/passwd"
+		if cut -d: -f1 "${__object:?}/explorer/passwd" | grep -qxF -e "${name}"
+		then
+			# user exists already
+			for property in *
+			do
+				unset -v current_value field
+				new_value=$(cat "${property}")
+				file="${__object:?}/explorer/passwd"
 
-          case ${property}
-          in
-             (gid)
-                if echo "${new_value}" | grep -q '^[0-9][0-9]*$'
-                then
-                   field=4
-                else
-                   # We were passed a group name.  Compare the gid in
-                   # the user's /etc/passwd entry with the gid of the
-                   # group returned by the group explorer.
-                   gid_from_group=$(awk -F: '{ print $3 }' "${__object:?}/explorer/group")
-                   gid_from_passwd=$(awk -F: '{ print $4 }' "${file}")
-                   if [ "${gid_from_group}" != "${gid_from_passwd}" ]
-                   then
-                      current_value=${gid_from_passwd}
-                   else
-                      current_value=${new_value}
-                   fi
-                fi
-                ;;
-             (password)
-                field=2
-                file="${__object:?}/explorer/shadow"
-                ;;
-             (comment) field=5 ;;
-             (home)    field=6 ;;
-             (shell)   field=7 ;;
-             (uid)     field=3 ;;
-             (create-home) continue;; # Does not apply to user modification
-             (system) continue;; # Does not apply to user modification
-             (state) continue;; # Does not apply to user modification
-             (remove-home) continue;; # Does not apply to user modification
-          esac
+				case ${property}
+				in
+					(password)
+						field=2
+						file="${__object:?}/explorer/shadow"
+						;;
+					(uid)
+						field=3
+						;;
+					(gid)
+						if expr "${new_value}" : '[0-9][0-9]*$' >/dev/null 2>&1
+						then
+							field=4
+						else
+							# We were passed a group name.  Compare the gid in
+							# the user's /etc/passwd entry with the gid of the
+							# group returned by the group explorer.
+							gid_from_group=$(cut -d: -f3 "${__object:?}/explorer/group")
+							gid_from_passwd=$(cut -d: -f4 "${file}")
+							if test "${gid_from_group}" = "${gid_from_passwd}"
+							then
+								current_value=${new_value}
+							else
+								current_value=${gid_from_passwd}
+							fi
+						fi
+						;;
+					(comment)
+						field=5
+						;;
+					(home)
+						field=6
+						;;
+					(shell)
+						field=7
+						;;
+					(create-home|system|remove-home)
+						# does not apply to user modification
+						continue
+						;;
+					(state)
+						# does not apply to user modification
+						continue
+						;;
+				esac
 
-          # If we haven't already set $current_value above, pull it from the
-          # appropriate file/field.
-          if [ -z "${current_value}" ]
-          then
-             export field
-             current_value=$(awk -F: '{ print $ENVIRON["field"] }' < "${file}")
-          fi
+				# if we haven't already set $current_value above, pull it from
+				# the appropriate file/field
+				: "${current_value:=$(cut -d : -f $((field)) <"${file}")}"
 
-          if [ "${new_value}" != "${current_value}" ]
-          then
-              set -- "$@" "$(shorten_property "${property}")" "${new_value}"
-          fi
-       done
+				if test "${new_value}" != "${current_value}"
+				then
+					set -- "$@" "$(shorten_property "${property}")" "${new_value}"
+				fi
+			done
 
-       if [ $# -gt 0 ]
-       then
-          echo mod >>"${__messages_out:?}"
+			if test $# -gt 0
+			then
+				do_user mod "${name}" "$@"
+				echo mod >>"${__messages_out:?}"
+			fi
+		else
+			# user does not already exist
 
-          do_user mod "${name}" "$@"
-       else
-          :
-       fi
-    else
-        echo add >>"${__messages_out:?}"
-        for property in *
-        do
-            [ "${property}" = 'state' ] && continue
-            [ "${property}" = 'remove-home' ] && continue
-            new_value=$(cat "${property}")
-            if [ -z "${new_value}" ]
-            then       # Boolean values have no value
-              set -- "$@" "$(shorten_property "${property}")"
-            else
-              set -- "$@" "$(shorten_property "${property}")" "${new_value}"
-            fi
-        done
+			for property in *
+			do
+				case ${property}
+				in
+					(remove-home)
+						continue ;;
+					(state)
+						continue ;;
+					(*)
+						new_value=$(cat "${property}")
 
-       do_user add "${name}" "$@"
-    fi
-elif [ "${state}" = 'absent' ]
-then
-    if cut -d: -f1 "${__object:?}/explorer/passwd" | grep -qxF -e "${name}"
-    then
-        #user exists, but state != present, so delete it
-        set --
-        if [ -f "${__object:?}/parameter/remove-home" ]
-        then
-            set -- "$@" -r
-        fi
+						# boolean options have no value, so new_value must be
+						# conditional
+						set -- "$@" "$(shorten_property "${property}")" ${new_value:+"${new_value}"}
+						;;
+				esac
+			done
 
-        do_user del "${name}" "$@"
-        echo "userdel $*" >>"${__messages_out:?}"
-    fi
-else
-    printf 'Invalid --state: %s\n' "${state}" >&2
-fi
+			do_user add "${name}" "$@"
+			echo add >>"${__messages_out:?}"
+		fi
+		;;
+	(absent)
+		if cut -d: -f1 "${__object:?}/explorer/passwd" | grep -qxF -e "${name}"
+		then
+			# user exists, but --state absent, so delete it
+			set --
+			if test -f "${__object:?}/parameter/remove-home"
+			then
+				set -- "$@" -r
+			fi
+
+			do_user del "${name}" "$@"
+			echo del >>"${__messages_out:?}"
+			# legacy, use del only in the future, like in the other cases
+			echo "userdel $*" >>"${__messages_out:?}"
+		fi
+		;;
+	(*)
+		printf 'Invalid --state: %s\n' "${state_should}" >&2
+		exit 1
+		;;
+esac
