Use balanced parentheses for case labels
Looking at the unbalanced parenstheses triggers me :-)
I also aligned all ;; with the block they're ending.
Also ;; the last label even if not required by POSIX.

diff --git a/type/__package_dpkg/gencode-remote b/type/__package_dpkg/gencode-remote
--- a/type/__package_dpkg/gencode-remote
+++ b/type/__package_dpkg/gencode-remote
@@ -37,16 +37,16 @@ state_should=''
 
 case ${state}
 in
-    present)
+    (present)
         echo "dpkg --install /var/cache/apt/archives/${__object_id:?}"
         echo 'installed' >> "${__messages_out:?}"
         ;;
-    absent)
+    (absent)
         [ -f "${__object:?}/parameter/purge-if-absent" ] \
             && action='--purge' \
             || action='--remove'
         echo "dpkg ${action} ${__object_id%%_*}"
         echo "removed (${action})" >> "${__messages_out:?}"
         ;;
-    *)  echo "ERROR: unknown state '${state}'" >&2 ;;
+    (*)  echo "ERROR: unknown state '${state}'" >&2 ;;
 esac
diff --git a/type/__pyvenv/manifest b/type/__pyvenv/manifest
--- a/type/__pyvenv/manifest
+++ b/type/__pyvenv/manifest
@@ -29,24 +29,24 @@ mode=$(cat "${__object:?}/parameter/mode")
 
 case ${state_should}
 in
-    present)
+    (present)
         case $(cat "${__global:?}/explorer/os")
         in
-            debian|ubuntu)
+            (debian|ubuntu)
                 __package python3-venv
-            ;;
+                ;;
         esac
-    ;;
+        ;;
 
-    absent)
+    (absent)
         __directory "${__object_id:?}" --state absent \
             --owner "${owner}" \
             --group "${group}" \
             --mode "${mode}"
-    ;;
+        ;;
 
-    *)
-        echo "Unknown state: ${state_should}" >&2
+    (*)
+        printf 'Invalid --state: %s\n' "${state_should}" >&2
         exit 1
-    ;;
+        ;;
 esac
