[type/__package_pip] Implement safe quoting
Also removed copyrights since no more code is left.

diff --git a/type/__package_pip/gencode-remote b/type/__package_pip/gencode-remote
--- a/type/__package_pip/gencode-remote
+++ b/type/__package_pip/gencode-remote
@@ -1,8 +1,5 @@
 #!/bin/sh -e
 #
-# 2012 Nico Schottelius (nico-cdist at schottelius.org)
-# 2016 Darko Poljak (darko.poljak at gmail.com)
-# 2021 Matthias Stecher (matthiasstecher at gmx.de)
 # 2022 Dennis Camera (cdist at dtnr.ch)
 #
 # This file is part of cdist.
@@ -20,9 +17,8 @@
 # You should have received a copy of the GNU General Public License
 # along with cdist. If not, see <http://www.gnu.org/licenses/>.
 #
-#
-# Development supported by Local AG (www.local.ch)
-#
+
+quote() { printf '%s\n' "$*" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'/"; }
 
 state_is=$(cat "${__object:?}/explorer/state")
 state_should=$(cat "${__object:?}/parameter/state")
@@ -34,40 +30,34 @@ requirement=$(cat "${__object:?}/explorer/requirement")
 
 pip=$(cat "${__object:?}/explorer/pip")
 test -n "${pip}" || {
-    echo 'Could not find pip.' >&2
-    echo 'Please make sure that pip is installed or specify the command to use in --pip.' >&2
-    exit 1
+	echo 'Could not find pip.' >&2
+	echo 'Please make sure that pip is installed or specify the command to use in --pip.' >&2
+	exit 1
 }
 
-runasparam="$__object/parameter/runas"
-if [ -f "$runasparam" ]
-then
-    runas=$(cat "$runasparam")
-else
-    runas=""
-fi
+runas=$(cat "${__object:?}/parameter/runas" 2>/dev/null || :)
 
-case "$state_should" in
-    present)
-        if [ "$runas" ]
-        then
-            echo "su -c \"$pip install -q '$requirement'\" $runas"
-        else
-            echo "$pip install -q '$requirement'"
-        fi
-        echo "installed" >> "$__messages_out"
-    ;;
-    absent)
-        if [ "$runas" ]
-        then
-            echo "su -c \"$pip uninstall -q -y '$requirement'\" $runas"
-        else
-            echo "$pip uninstall -q -y '$requirement'"
-        fi
-        echo "removed" >> "$__messages_out"
-    ;;
-    *)
-        echo "Unknown state: $state_should" >&2
-        exit 1
-    ;;
+do_cmd() {
+	if test -n "${runas}"
+	then
+		printf 'su -l %s -c %s\n' "$(quote "${runas}")" "$(quote "$1")"
+	else
+		printf '%s\n' "$1"
+	fi
+}
+
+case ${state_should}
+in
+	(present)
+		do_cmd "${pip} install -q $(quote "${requirement}")"
+		echo installed >> "${__messages_out:?}"
+		;;
+	(absent)
+		do_cmd "${pip} uninstall -q -y $(quote "${requirement}")"
+		echo removed >> "${__messages_out:?}"
+		;;
+	(*)
+		printf 'Invalid --state: %s\n' "${state_should}" >&2
+		exit 1
+		;;
 esac
